#pragma once

#include <stdint.h>
#include <stdbool.h>
#include <SDL2/SDL.h>

typedef struct keyb_t
{
	uint8_t keyRepeat, keyPressed;
	bool ignoreCurrKeyUp, ignoreTextEditKey, numPadPlusPressed;
	bool keyModifierDown, leftCommandPressed, leftWinKeyDown;
	bool leftShiftPressed, leftCtrlPressed, leftAltPressed;
} keyb_t;

extern keyb_t keyb; // ft2_keyboard.c

enum
{
	KEYMAP_ACTION_SHOW_ADV_EDIT = 0,
	KEYMAP_ACTION_SHOW_ABOUT,
	KEYMAP_ACTION_SHOW_CONFIG,
	KEYMAP_ACTION_SHOW_DISK_OP,
	KEYMAP_ACTION_SHOW_HELP,
	KEYMAP_ACTION_SHOW_INST_EDITOR,
	KEYMAP_ACTION_SHOW_INST_EDITOR_EXT,
	KEYMAP_ACTION_SHOW_NIBBLES,
	KEYMAP_ACTION_SHOW_PATTERN_EDITOR,
	KEYMAP_ACTION_SHOW_SAMPLE_EDITOR_EXT,
	KEYMAP_ACTION_SHOW_TRANSPOSE,
	KEYMAP_ACTION_CONFIG_AUDIO_TAB,
	KEYMAP_ACTION_CONFIG_LAYOUT_TAB,
	KEYMAP_ACTION_CONFIG_MISC_TAB,
	KEYMAP_ACTION_CONFIG_MIDI_TAB,
	KEYMAP_ACTION_SHOW_TRIM,
	KEYMAP_ACTION_SHOW_SAMPLE_EDITOR,
	KEYMAP_ACTION_TOGGLE_EXT_PATTERN,
	KEYMAP_ACTION_CLOSE_TO_PATTERN,
	KEYMAP_ACTION_TOGGLE_FULLSCREEN,
	KEYMAP_ACTION_PLAY_FROM_JUMP_1,
	KEYMAP_ACTION_PLAY_FROM_JUMP_2,
	KEYMAP_ACTION_PLAY_FROM_JUMP_3,
	KEYMAP_ACTION_PLAY_FROM_JUMP_4,
	KEYMAP_ACTION_SET_JUMP_1,
	KEYMAP_ACTION_SET_JUMP_2,
	KEYMAP_ACTION_SET_JUMP_3,
	KEYMAP_ACTION_SET_JUMP_4,
	KEYMAP_ACTION_JUMP_CH_0,
	KEYMAP_ACTION_JUMP_CH_1,
	KEYMAP_ACTION_JUMP_CH_2,
	KEYMAP_ACTION_JUMP_CH_3,
	KEYMAP_ACTION_JUMP_CH_4,
	KEYMAP_ACTION_JUMP_CH_5,
	KEYMAP_ACTION_JUMP_CH_6,
	KEYMAP_ACTION_JUMP_CH_7,
	KEYMAP_ACTION_JUMP_CH_8,
	KEYMAP_ACTION_JUMP_CH_9,
	KEYMAP_ACTION_JUMP_CH_10,
	KEYMAP_ACTION_JUMP_CH_11,
	KEYMAP_ACTION_JUMP_CH_12,
	KEYMAP_ACTION_JUMP_CH_13,
	KEYMAP_ACTION_JUMP_CH_14,
	KEYMAP_ACTION_JUMP_CH_15,
	KEYMAP_ACTION_ALT_C_CONTEXT,
	KEYMAP_ACTION_ALT_V_CONTEXT,
	KEYMAP_ACTION_ALT_X_SAMPLE_CUT,
	KEYMAP_ACTION_ALT_Z_SAMPLE_ZOOM_OUT,
	KEYMAP_ACTION_CTRL_V_CONTEXT,
	KEYMAP_ACTION_SHIFT_V_TRACK_VOL,
	KEYMAP_ACTION_MACRO_READ_1,
	KEYMAP_ACTION_MACRO_READ_2,
	KEYMAP_ACTION_MACRO_READ_3,
	KEYMAP_ACTION_MACRO_READ_4,
	KEYMAP_ACTION_MACRO_READ_5,
	KEYMAP_ACTION_MACRO_READ_6,
	KEYMAP_ACTION_MACRO_READ_7,
	KEYMAP_ACTION_MACRO_READ_8,
	KEYMAP_ACTION_MACRO_READ_9,
	KEYMAP_ACTION_MACRO_READ_10,
	KEYMAP_ACTION_MACRO_WRITE_1,
	KEYMAP_ACTION_MACRO_WRITE_2,
	KEYMAP_ACTION_MACRO_WRITE_3,
	KEYMAP_ACTION_MACRO_WRITE_4,
	KEYMAP_ACTION_MACRO_WRITE_5,
	KEYMAP_ACTION_MACRO_WRITE_6,
	KEYMAP_ACTION_MACRO_WRITE_7,
	KEYMAP_ACTION_MACRO_WRITE_8,
	KEYMAP_ACTION_MACRO_WRITE_9,
	KEYMAP_ACTION_MACRO_WRITE_10,
	KEYMAP_ACTION_TRANSP_ALL_TRACK_DN,
	KEYMAP_ACTION_TRANSP_ALL_PATT_DN,
	KEYMAP_ACTION_TRANSP_ALL_BLOCK_DN,
	KEYMAP_ACTION_TRANSP_ALL_TRACK_UP,
	KEYMAP_ACTION_TRANSP_ALL_PATT_UP,
	KEYMAP_ACTION_TRANSP_ALL_BLOCK_UP,
	KEYMAP_ACTION_TRANSP_CUR_TRACK_DN,
	KEYMAP_ACTION_TRANSP_CUR_PATT_DN,
	KEYMAP_ACTION_TRANSP_CUR_BLOCK_DN,
	KEYMAP_ACTION_TRANSP_CUR_TRACK_UP,
	KEYMAP_ACTION_TRANSP_CUR_PATT_UP,
	KEYMAP_ACTION_TRANSP_CUR_BLOCK_UP,
	KEYMAP_ACTION_OCTAVE_0,
	KEYMAP_ACTION_OCTAVE_1,
	KEYMAP_ACTION_OCTAVE_2,
	KEYMAP_ACTION_OCTAVE_3,
	KEYMAP_ACTION_OCTAVE_4,
	KEYMAP_ACTION_OCTAVE_5,
	KEYMAP_ACTION_OCTAVE_6_F7,
	KEYMAP_ACTION_OCTAVE_6_F8,
	KEYMAP_ACTION_JUMP_TO_POS_1,
	KEYMAP_ACTION_JUMP_TO_POS_2,
	KEYMAP_ACTION_JUMP_TO_POS_3,
	KEYMAP_ACTION_JUMP_TO_POS_4,
	KEYMAP_ACTION_CUT_TRACK,
	KEYMAP_ACTION_CUT_PATTERN,
	KEYMAP_ACTION_CUT_BLOCK,
	KEYMAP_ACTION_COPY_TRACK,
	KEYMAP_ACTION_COPY_PATTERN,
	KEYMAP_ACTION_COPY_BLOCK,
	KEYMAP_ACTION_PASTE_TRACK,
	KEYMAP_ACTION_PASTE_PATTERN,
	KEYMAP_ACTION_PASTE_BLOCK,

	KEYMAP_ACTION_COUNT
};

int8_t scancodeKeyToNote(SDL_Scancode scancode);
void keyUpHandler(SDL_Scancode scancode, SDL_Keycode keycode);
void keyDownHandler(SDL_Scancode scancode, SDL_Keycode keycode, bool keyWasRepeated);
void readKeyModifiers(void);

void keymapResetDefaults(void);
int32_t keymapGetBindingPacked(int32_t action);
bool keymapSetBinding(int32_t action, SDL_Keycode keycode, uint8_t modsMask);
